### ISSUE TITLE
Cannot download the dataset.

### ISSUE THREAD

**Issue by xytmhy** [codeslake/DMENet#1]
Hi,
I noticed there are two links of your dataset, the one from **dropbox** cannot be opened, and the one of **google drive** has nothing in the folder. I guess that you might have not prepared yet.

**Comment by codeslake** [comment]
Sorry for the late reply and thank you for noticing the problems!
I've changed all the problematic links to right ones.
(Link for the dataset has not been changed though, would you check one more time whether they are OK?)
