### ISSUE TITLE
Output of DMENet

### ISSUE THREAD

**Issue by chanwental** [codeslake/DMENet#10]
Hi，Dr.Lee.

When I test the network，I get the file named as _xxxx_2_defocus_map_out.png_.

I want to know what value is saved in this file .

Thank you and look forward to your reply!

Best,
Cheng

**Comment by codeslake** [comment]
It contains the value of sigma, if you test our model with the model checkpoint that we shared.
(We have retrained the model with SYNDOF dataset containing sigma value. When we read the dataset, we did not divide it by 15.)


If you train the model with SYNDOF that we shared,  xxxx_2_defocus_map_out.png. will contain max-normalized max_coc.
If you want to get sigma, you have to do ((network_ouput*15) - 1)/2 during training and testing.

Sorry for the confusion.

**Comment by chanwental** [comment]
I am still confused.

The file named as xxxx_2_defocus_map_out.png is generated when I test the model with the model checkpoint that you shared.
1)The input is synthetic image generateed by your SYNDOF code (max_coc=29). So the  corresponding blur_map is known and the max_sigma is known (max_sigma=7). But the range of value in _xxxx_2_defocus_map_out.png_ is not around [0, 7].
2)The blur_map is not visible. That's reasonable because It contains the value of sigma(*10).
However, the xxxx_2_defocus_map_out.png is  visible. The values saved in it don't seem to be _sigma_.

I read a _xxxx_2_defocus_map_out.png_ as follows：

_file_name = 'logs/DMENet_BDCS/samples/1_test/2020_10_29/19-29/out/0000.png'
image = ((cv2.imread(file_name, cv2.IMREAD_UNCHANGED)))_

**Comment by codeslake** [comment]
I apologize again for the confusion.

My previous answer was wrong.

0. We have not retrained the network SYNDOF containing sigma value.

1. If you are using the model and checkpoint that I shared for testing an image, the value of  _xxxx_2_defocus_map_out.png_ contains _"max-normalized" CoC_. If you want to get actual sigma value, you will have to do.

_sigma = ((defocus_map * 15)  - 1) / 2._

**Comment by chanwental** [comment]
I found that the maximum of values in a defocus_map is around 200. And every defocus_map has different one.
It doesn't seem to be the value normalized.

If _max_defocus_map =200_, _max_sigma_ is 1499.5.

**Comment by codeslake** [comment]
I don't get it. The range of defocus_map should between 0 and 1 as the final layer of the network is sigmoid.

Try this.

_defocus_map = ((cv2.imread(file_name, cv2.IMREAD_UNCHANGED))) / 255.
sigma = ((defocus_map * 15) - 1) / 2._

**Comment by chanwental** [comment]
Thank you. I get it.
