### ISSUE TITLE
All-in-focus image generation

### ISSUE THREAD

**Issue by chanwental** [codeslake/DMENet#12]
Hi，Dr.Lee.

Thanks for your wonderful work!

In this paper, you generate the all-in-focus images using DMENet with non-blind image deconvolution technique.
Could you share the code about it?

Best,
chanwental

**Comment by codeslake** [comment]
Hi, @chanwental.

I actually have been working on sharing the deconvolution code.
The code will be uploaded to this repo, probably in 1 or 2 days.

Thanks!

**Comment by chanwental** [comment]
That's great!
Thank you very much!

**Comment by codeslake** [comment]
Hi, @chanwental.

Checkout the [deconvolution code](https://github.com/codeslake/DMENet/tree/master/deconvolution)!
Let me know if there is any question :)

Best,

**Comment by codeslake** [comment]
closing the issue

**Comment by codeslake** [comment]
I have found some bugs.
As it is important to upload accurate code, I will fix the bug and re-upload the deconvolution code.
Sorry for the issue.

**Comment by codeslake** [comment]
Fixed the bug, closing the issue.

**Comment by chanwental** [comment]
> I have found some bugs.
> As it is important to upload accurate code, I will fix the bug and re-upload the deconvolution code.
> Sorry for the issue.

I can't find the deconvolution code after re-uploading .

**Comment by codeslake** [comment]
Hi, @chanwental.

I am fixing the code again. I will post the final code in a day. Thanks!

**Comment by codeslake** [comment]
@chanwental 
Fixed the bug, closing the issue.

Thanks!

**Comment by chanwental** [comment]
> @chanwental
> Fixed the bug, closing the issue.
> 
> Thanks!

@codeslake Thank you so much!
