### ISSUE TITLE
RTF dataset

### ISSUE THREAD

**Issue by pengjw98** [codeslake/DMENet#13]
Hi, 

Could you please share the original RGB images in RTF dataset?

Best Regards,
pengjw98

**Comment by codeslake** [comment]
Hi, @pengjw98 

I don't want to share the dataset without the author's permission.
But if you contact the author (Laurent, laurentdandres@gmail.com), he will kindly share the dataset and necessary information with you.

You might wanna hang on, as I've just contacted him personally, asking if it is alright to share the dataset in the repository.

Best,

**Comment by pengjw98** [comment]
Thank you very much!

**Comment by codeslake** [comment]
@pengjw98, refer [here](https://github.com/codeslake/DMENet/tree/master/evaluation#L1) for the download link.

**Comment by codeslake** [comment]
@pengjw98, refer [here](https://github.com/codeslake/DMENet/tree/master/evaluation/RTF#2) for the dataset.

**Comment by pengjw98** [comment]
Thank you for your reply. It really helps me.



发自我的iPhone


------------------ Original ------------------
From: Junyong Lee ***@***.***&gt;
Date: Tue,Apr 6,2021 9:22 AM
To: codeslake/DMENet ***@***.***&gt;
Cc: Suraimu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [codeslake/DMENet] RTF dataset (#13)

**Comment by pengjw98** [comment]
Has the link been updated? I still couldn't find the original RGB images in dataset.

**Comment by codeslake** [comment]
Hi @pengjw98,

Sorry for that. Please check [here](https://github.com/codeslake/DMENet/tree/master/evaluation/RTF#19). I've just posted the link for the original zip file provided by the author.

Best,

**Comment by pengjw98** [comment]
Thanks a lot
