### ISSUE TITLE
cannot download the dataset and pretrained_model

### ISSUE THREAD

**Issue by shyying123** [codeslake/DMENet#14]
Hi,
I noticed there are two links of your dataset, pretrained_model, but these links cannot open, can you provide some new links? thank u.

**Comment by codeslake** [comment]
Hi, @shyying123.

I've just tried all the links but they are working fine.
What exactly happens when you click them?

**Comment by shyying123** [comment]
> Hi, @shyying123.
> 
> I've just tried all the links but they are working fine.
> What exactly happens when you click them?

hi, I find the question, have solved this problem, thank you.
