### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by kqm315** [codeslake/DMENet#15]
Hello, when I downloaded the DataSet of DMEnet to a quarter part, it was always forbidden. Do you have any solution? Thank you

**Comment by codeslake** [comment]
https://postechackr-my.sharepoint.com/:u:/g/personal/junyonglee_postech_ac_kr/EZsNnnayLAxNnT9UcM9GD8cBNaYzVbir6h4E4gJd3uySDQ?e=fAfkki

That's strange, I can download mine without a problem. I've created a link using MS one drive. Will you try above link?

**Comment by kqm315** [comment]
Thanks for your reply, this link is useful.
Best regards，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junyong ***@***.***&gt;; 
发送时间: 2021年6月1日(星期二) 晚上7:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeslake/DMENet] Problem (#15)





 
https://postechackr-my.sharepoint.com/:u:/g/personal/junyonglee_postech_ac_kr/EZsNnnayLAxNnT9UcM9GD8cBNaYzVbir6h4E4gJd3uySDQ?e=fAfkki
 
That's strange, I can download mine without a problem. I've created a link using MS one drive. Will you try above link?
