### ISSUE TITLE
cannot download the dataset

### ISSUE THREAD

**Issue by 6fly6** [codeslake/DMENet#17]
I can't download the dataset, it always failed to download to the end.
can you check the link and  provide some new links? thank u.

**Comment by codeslake** [comment]
Will you try [this one](https://postechackr-my.sharepoint.com/:u:/g/personal/junyonglee_postech_ac_kr/EZsNnnayLAxNnT9UcM9GD8cBK65R8yXg9vyEd0lmKe88Zw)?

**Comment by Qiu-yuanhong** [comment]
I also can't download the dataset, it always failed at the end.

**Comment by 6fly6** [comment]
Thank you for your reply. The link you sent can be used. I downloaded it successfully. Thank you very much.

**Comment by codeslake** [comment]
Good to hear that! I will add the link in the readme. Closing the issue.
