### ISSUE TITLE
Generate ground-truth binary blur masks

### ISSUE THREAD

**Issue by 6fly6** [codeslake/DMENet#18]
Hi,thank you very much for this implementation.
I used my own image to generate defocus map successfully.But what I need are masks.If I use my own images, how can I generate the ground truth binary blur masks.

**Comment by codeslake** [comment]
Hi, 

To make a binary blur mask, you will have to apply the empirically chosen threshold to the defocus map.

If you have GT blur masks in your dataset, I would choose a threshold value maximizing the mean average precision (mAP).
If you don't have GT masks, you will have to play with threshold values making the result the best.

Thanks!

**Comment by 6fly6** [comment]
Thank you for your reply. I'll try.
