### ISSUE TITLE
Issue with Pretrained Weights

### ISSUE THREAD

**Issue by Mithrandir117** [codeslake/DMENet#2]
When I load your pretrained weights I am getting a lot of warnings from tensorlayer that tensors are not found (e.g. Warning: Tensor named main_net/defocus_net/decoder/u0/c1_1/bias:0 not found in network.). Also, the resulting defocus map is all zeros for any image I tested on. I am using all the recommended software versions (python, CUDA, etc.). Have you seen this problem before? Thanks in advance for your help.

**Comment by codeslake** [comment]
Hi, you should you tensorlayer version 1.2.1, if I remember correctly.
Thanks and I am closing this issue.
