### ISSUE TITLE
How to set the lambda in deconvolution

### ISSUE THREAD

**Issue by xytmhy** [codeslake/DMENet#20]
Hi,

I want to use the deconvolution code and I find for different dataset, you use different lambda in line 28-37, run_DMENet_deconv.m.

Any clue how to set this? if I want to try it in my own image. Thanks.

**Comment by codeslake** [comment]
Hi, @xytmhy. 

The lambda value is empirically chosen. You will have to play with the value to get the deconvolution result.
Best,
