### ISSUE TITLE
test dataset

### ISSUE THREAD

**Issue by ByChelsea** [codeslake/DMENet#21]
Hi,
  Thanks for your great work. 
  Image names in the test dataset (SYNDOF) do not correspond and I don't know how to read these images...
  The names in the "gt" file are "0000.png, 0001.png ...", but in the "image" file, they are "SYNTHIA_RAND_CITYSCAPES_image_0000017_f_85_fp_0_17_A_9_3.png, ..."

**Comment by codeslake** [comment]
Hi,
You may obtain the file names of each folder first, and sort each of them, then read each image from the sorted lists.

**Comment by ByChelsea** [comment]
Thank you! I'll try.

**Comment by ByChelsea** [comment]
By the way, the size of the images in the "gt" folder are "1280x752", but the sizes in the "image" folder are "1280x760". How should I deal with this?

**Comment by codeslake** [comment]
Apply a mod crop on images in the `image` folder:
```python
def refine_image(img):
    h, w = img.shape[:2]

    return img[0 : h - h % 16, 0 : w - w % 16]
```

**Comment by ByChelsea** [comment]
Thanks again and have a nice day~
