### ISSUE TITLE
Tensorflow v1 is no longer supported

### ISSUE THREAD

**Issue by KMCzajkowski** [codeslake/DMENet#23]
Will TF v2 version be available? Tensorflow v1 is no longer supported by pip and thus I cannot install DMENet anymore.

**Comment by codeslake** [comment]
I am not sure if I can transport from TF v1 to TF v2 including the checkpoint.
I will try when I have time.
Did you try [docker installation](https://github.com/codeslake/DMENet#prerequisites) (option 2)?

And are you sure TF v1 is not supported by pip?
I've made the docker image with TF installed using pip few days ago.

**Comment by KMCzajkowski** [comment]
Thank you so much for such a quick response. I didn't try the docker installation. I will have a look at this. 
<br>
pip install "tensorflow<2.0.0"
<br>
gives
<br>
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0.0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0)
ERROR: No matching distribution found for tensorflow<2.0.0

**Comment by KMCzajkowski** [comment]
I just wanted to let you know that the code works fine in docker. Thank you for your hint!
