### ISSUE TITLE
what is the version of tensorlayer?

### ISSUE THREAD

**Issue by PeiqinSun** [codeslake/DMENet#3]
In your readme.md, the version of tensorlayer is 1.2.1, but 1.2.1 doesn't work. 
Is there a update of tensorlayer? if yes, what is the newest version of tensorlayer and tensorflow?

**Comment by codeslake** [comment]
Sorry for the late reply. You should use tensorlayer 1.2.1. If I remember correctly, there is an error on upsampling layer if you use different version. Would you share the error message? Thanks.

**Comment by GitHub0830** [comment]
The version of tensorlayer is 1.2.1 and  there's an error:  
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from utils import *
  File "./DMENet-master/utils.py", line 3, in <module>
    from tensorlayer.prepro import *
ModuleNotFoundError: No module named 'tensorlayer.prepro'

Looking forward to your reply.

**Comment by codeslake** [comment]
Uhm.. I will clarify exact versions of required libraries ASAP. For now, try tensorflow 1.13.1 and tensorlayer 1.11.1. I've just checked my old docker image with the libraries and it works OK.

**Comment by GitHub0830** [comment]
Well done! My problem is solved.
Thank you.

**Comment by codeslake** [comment]
Apology for the late response once again! As I mentioned, I will update the repo with the clear versions of the libraries!
