### ISSUE TITLE
Issue with training with GPU

### ISSUE THREAD

**Issue by GitHub0830** [codeslake/DMENet#4]
Can you tell me how to train with GPU?

I have specified GPU, 
" os.environ["CUDA_VISIBLE_DEVICES"] = '8' "
but I failed and it still output：
"2020-05-06 16:31:04.495971: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-06 16:31:04.526384: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199940000 Hz"

Looking forward to your reply.

**Comment by codeslake** [comment]
Have you downloaded TensorFlow-gpu?
I've never faced such a problem. Also, please make sure that you are using the appropriate TensorFlow & tensorlayer version as mentioned in the README.

Best,

**Comment by codeslake** [comment]
closing the issue as there is no reply for a long period.
