### ISSUE TITLE
How to apply deconvolution from masks?

### ISSUE THREAD

**Issue by Ossss2** [codeslake/DMENet#6]
Hi,
In the paper it was written: "We then use non-blind image deconvolution technique leveraging hyper-Laplacian [16]; to handle spatially-varying deblur, we applied deconvolution to the decomposed layers, and compose deconvolved layer images."

While using the code, it correctly generates the masks, but didn't apply deconvolution. Is the code provided in this repository? If not, do you have any idea how to correctly apply deconvolution based on the generated masks?

ps: The code is very messy. Barelly got it working on Debian, due to old packages and conflicting dependencies. Please consider using pytorch with PEP8 style on next projects.

**Comment by codeslake** [comment]
Leave your email address. I will send you the code for the deblurring.

And yes, we are aware of the code issues. We are planning to implement the code in PyTorch.
Best,

**Comment by Saurabh528** [comment]
@codeslake I also need this code please send me pandeysaurabh335@gmail.com

**Comment by codeslake** [comment]
Here I attach the link for the code.

https://www.dropbox.com/s/7lib13ff5jivahl/refocus.zip?dl=0

Best,
