### ISSUE TITLE
Generate Defocus Maps

### ISSUE THREAD

**Issue by Saurabh528** [codeslake/DMENet#7]
Hello, thank you very much for this implementation. 
I want to know how can I generate maps for my custom images. I don't have the ground truth images for them. I have created test folder in datasets and put my images there but it asks for gt images. How can I just generate the defocus maps without the ground truth values. ?

**Comment by codeslake** [comment]
Hi Saurabh, 

You don’t need binary images.
The code requires it, but the network doesn’t actually use it.
I believe I left it there for metric evaluations such as accuracy.

Just for now, use the same path (path for your testing images) for config.TEST.cuhk_img_path and config.TEST.cuhk_binary_map_path.

Best,
Junyong
