### ISSUE TITLE
The max_coc of datasets is not 28.

### ISSUE THREAD

**Issue by chanwental** [codeslake/DMENet#9]
Hi，
I read a blur_map in your dataset as follows：
image = (np.float32(cv2.imread(file_name, cv2.IMREAD_UNCHANGED))/10.)[:, :, 1].
Then the maximum of image is 15. #15=(61-1)/4
It implys max_coc=61, which is not consistent with 28 in your paper.
What is the problem?

**Comment by codeslake** [comment]
Thank your for your interest in our work!
I am sorry for the confusion in the code.

The SYNDOF dataset that I shared on the github, actually generated from the initial version of SYNDOF generation code.
The equation (https://github.com/codeslake/SYNDOF/blob/5fdef6718088a4fa02acd4867602e5236e2c7271/blur_by_depth.m#L245) is the refined version after the paper is publicized, for better readability.

At the initial version of the SYNDOF generation code, I saved the x value in the defocus map, where “sigma = ((x - 1) * 2) / 4”.
(The equation makes the coc_max=28 when x=15)
And it is why I divide the defocus map with 15 in the DMENet code.

But please note that, there is actually no difference between the codes for initial SYNDOF generation and the released SYNDOF generation. (i.e., defocused images are the same for [old_SYNODF(image, depth, 15) and new_SYNDOF(image,depth,28)])
The only difference is which value I saved for the defocus maps in SYNDOF.
